# Generated by Django 5.0.1 on 2024-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(default='BTCUSDT', max_length=30)),
                ('time', models.DateTimeField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=50, max_digits=200)),
                ('high', models.DecimalField(decimal_places=50, max_digits=200)),
                ('low', models.DecimalField(decimal_places=50, max_digits=200)),
                ('close', models.DecimalField(decimal_places=50, max_digits=200)),
            ],
        ),
    ]
